# Generated by Django 5.2.7 on 2025-11-23 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("객관식", "Single Choice"),
                            ("다중선택", "Multiple Choice"),
                            ("주관식 (단일정답)", "Short Answer"),
                            ("주관식 (복수정답)", "Short Answer Multiple"),
                        ],
                        default="객관식",
                        max_length=20,
                        verbose_name="문제 유형",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="문제 내용")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("하", "Easy"), ("중", "Medium"), ("상", "Hard")],
                        default="하",
                        max_length=2,
                        verbose_name="난이도",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="quiz_images/",
                        verbose_name="이미지",
                    ),
                ),
            ],
            options={
                "verbose_name": "문제",
                "verbose_name_plural": "문제",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="태그 이름"
                    ),
                ),
            ],
            options={
                "verbose_name": "태그",
                "verbose_name_plural": "태그",
            },
        ),
        migrations.CreateModel(
            name="ExamSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="문제 세트 이름"),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        to="quiz.question", verbose_name="포함된 문제들"
                    ),
                ),
            ],
            options={
                "verbose_name": "문제 세트",
                "verbose_name_plural": "퀴즈 관리 / 5. 문제 세트",
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(blank=True, max_length=200)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="choice_images/"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
            ],
            options={
                "verbose_name": "보기",
                "verbose_name_plural": "보기",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="퀴즈 제목")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("공통", "공통 (모든 교육생에게 표시)"),
                            ("공정", "공정 (해당 공정 교육생에게 우선 표시)"),
                        ],
                        default="공통",
                        max_length=10,
                        verbose_name="퀴즈 분류",
                    ),
                ),
                (
                    "generation_method",
                    models.CharField(
                        choices=[
                            ("랜덤", "난이도별 랜덤 출제 (기본)"),
                            ("지정", "지정 문제 세트 출제"),
                            ("태그", "태그 조합 랜덤 출제"),
                        ],
                        default="랜덤",
                        max_length=10,
                        verbose_name="문제 출제 방식",
                    ),
                ),
                (
                    "allowed_groups",
                    models.ManyToManyField(
                        blank=True, to="auth.group", verbose_name="응시 가능 그룹"
                    ),
                ),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="특정 인원에게만 이 시험을 지정하고 싶을 때 선택하세요.",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="개별 응시 허용 인원",
                    ),
                ),
                (
                    "associated_process",
                    models.ForeignKey(
                        blank=True,
                        help_text="퀴즈 분류가 '공정'인 경우에만 선택해주세요.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.process",
                        verbose_name="관련 공정",
                    ),
                ),
                (
                    "exam_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="quiz.examsheet",
                        verbose_name="선택된 문제 세트",
                    ),
                ),
                (
                    "required_tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="출제 방식이 '태그 조합'일 때, 선택한 태그가 포함된 문제들 중에서만 출제됩니다.",
                        to="quiz.tag",
                        verbose_name="출제 포함 태그",
                    ),
                ),
            ],
            options={
                "verbose_name": "퀴즈",
                "verbose_name_plural": "퀴즈",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
            ),
        ),
        migrations.AddField(
            model_name="examsheet",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.quiz",
                verbose_name="관련 퀴즈",
            ),
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("대기중", "Pending"),
                            ("승인됨", "Approved"),
                            ("완료됨", "Completed"),
                        ],
                        default="대기중",
                        max_length=10,
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[("개인 요청", "Individual"), ("그룹 배정", "Group")],
                        default="개인 요청",
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("attempt_number", models.IntegerField(default=0)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "응시 요청",
                "verbose_name_plural": "응시 요청",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="quiz.tag", verbose_name="태그"
            ),
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "is_pass",
                    models.BooleanField(default=False, verbose_name="합격 여부"),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("attempt_number", models.IntegerField(default=0)),
                (
                    "attempt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.quizattempt",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "최종 결과",
                "verbose_name_plural": "최종 결과",
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_answer_text",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_correct", models.BooleanField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.choice",
                    ),
                ),
                (
                    "test_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.testresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 답변",
                "verbose_name_plural": "사용자 답변",
            },
        ),
    ]
