# Generated by Django 5.2.7 on 2025-12-11 13:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_joined_at_alter_studentlog_action_taken"),
        ("quiz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "verbose_name": "문제 (Question Bank)",
                "verbose_name_plural": "문제 (Question Bank)",
            },
        ),
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                blank=True,
                related_name="quizzes",
                to="quiz.question",
                verbose_name="포함된 문제들 (지정 방식용)",
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choice_set",
                to="quiz.question",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="allowed_quizzes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="개별 응시 허용 인원",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="associated_process",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.process",
                verbose_name="관련 공정",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="exam_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="quiz.examsheet",
                verbose_name="선택된 문제 세트 (구버전)",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="required_tags",
            field=models.ManyToManyField(
                blank=True, to="quiz.tag", verbose_name="출제 포함 태그"
            ),
        ),
    ]
