# Generated by Django 5.2.7 on 2025-12-25 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_delete_studentlog"),
        ("quiz", "0002_alter_question_options_remove_question_quiz_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("warning", "⚠️ 경고"),
                            ("warning_letter", "📜 경위서"),
                            ("counseling", "💬 면담/알림"),
                            ("praise", "👏 칭찬"),
                            ("system", "🔔 시스템"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(verbose_name="내용")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "action_taken",
                    models.TextField(blank=True, null=True, verbose_name="조치 사항"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "학생 기록/알림",
                "verbose_name_plural": "학생 기록/알림 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
