# Generated by Django 5.2.7 on 2025-10-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="choice_images/"),
        ),
    ]
