# Generated by Django 5.2.7 on 2026-01-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentlog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("warning", "⚠️ 경고"),
                    ("warning_letter", "📜 경고장"),
                    ("counseling", "💬 면담/알림"),
                    ("praise", "👏 칭찬"),
                    ("system", "🔔 시스템"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
