# Generated by Django 5.2.7 on 2025-10-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_testresult_useranswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="attempt_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
