# Generated by Django 5.2.7 on 2025-10-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_quizattempt_testresult_attempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="attempt_number",
            field=models.IntegerField(default=0),
        ),
    ]
