# Generated by Django 5.2.7 on 2026-01-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_quizattempt_completed_at_quizattempt_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresult",
            name="is_viewed",
            field=models.BooleanField(default=False),
        ),
    ]
