# Generated by Django 5.2.7 on 2025-10-11 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_quizattempt_attempt_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("객관식", "Single Choice"),
                    ("다중선택", "Multiple Choice"),
                    ("주관식", "Short Answer"),
                ],
                default="객관식",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="short_answer_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="selected_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.choice",
            ),
        ),
    ]
