# Generated by Django 5.2.7 on 2025-10-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_question_question_type_useranswer_short_answer_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={
                "verbose_name": "3. 보기",
                "verbose_name_plural": "퀴즈 관리 / 3. 보기",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "verbose_name": "2. 문제",
                "verbose_name_plural": "퀴즈 관리 / 2. 문제",
            },
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={
                "verbose_name": "1. 퀴즈 종류",
                "verbose_name_plural": "퀴즈 관리 / 1. 퀴즈 종류",
            },
        ),
        migrations.AlterModelOptions(
            name="quizattempt",
            options={
                "verbose_name": "1. 응시 요청",
                "verbose_name_plural": "시험 결과 관리 / 1. 응시 요청",
            },
        ),
        migrations.AlterModelOptions(
            name="testresult",
            options={
                "verbose_name": "2. 최종 결과",
                "verbose_name_plural": "시험 결과 관리 / 2. 최종 결과",
            },
        ),
        migrations.AlterModelOptions(
            name="useranswer",
            options={
                "verbose_name": "3. 사용자 답변",
                "verbose_name_plural": "시험 결과 관리 / 3. 사용자 답변",
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="time_limit_minutes",
            field=models.IntegerField(default=30, verbose_name="제한 시간(분)"),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="시험 시작 시간"
            ),
        ),
    ]
