# Generated by Django 5.2.7 on 2026-01-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_quizresult_is_viewed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("객관식", "Single Choice"),
                    ("다중선택", "Multiple Choice"),
                    ("주관식 (단일정답)", "Short Answer"),
                    ("주관식 (복수정답)", "Short Answer Multiple"),
                ],
                default="객관식",
                max_length=50,
                verbose_name="문제 유형",
            ),
        ),
    ]
