# Generated by Django 5.2.7 on 2025-10-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_alter_choice_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="태그 이름"
                    ),
                ),
            ],
            options={
                "verbose_name": "4. 태그",
                "verbose_name_plural": "퀴즈 관리 / 4. 태그",
            },
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="time_limit_minutes",
        ),
        migrations.RemoveField(
            model_name="quizattempt",
            name="started_at",
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="quiz.tag", verbose_name="태그"
            ),
        ),
    ]
