# Generated by Django 5.2.7 on 2026-01-08 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_alter_question_question_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quizattempt",
            options={
                "verbose_name": "응시 요청/기록",
                "verbose_name_plural": "응시 요청/기록",
            },
        ),
        migrations.AlterModelOptions(
            name="useranswer",
            options={
                "verbose_name": "사용자 답변 상세",
                "verbose_name_plural": "사용자 답변 상세",
            },
        ),
        migrations.RenameField(
            model_name="quiz",
            old_name="associated_process",
            new_name="related_process",
        ),
        migrations.AddField(
            model_name="quiz",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description",
            field=models.TextField(blank=True, verbose_name="시험 설명"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="pass_score",
            field=models.IntegerField(default=80, verbose_name="합격 기준 점수"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="question_count",
            field=models.IntegerField(default=25, verbose_name="출제 문항 수"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="time_limit",
            field=models.IntegerField(default=30, verbose_name="제한 시간(분)"),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("low", "하"), ("medium", "중"), ("high", "상")],
                default="medium",
                max_length=10,
                verbose_name="난이도",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "객관식 (단일 정답)"),
                    ("multiple_select", "객관식 (복수 정답)"),
                    ("short_answer", "주관식 (단답형)"),
                    ("true_false", "OX 퀴즈"),
                ],
                default="multiple_choice",
                max_length=50,
                verbose_name="문제 유형",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="generation_method",
            field=models.CharField(
                choices=[
                    ("random", "랜덤 출제 (태그 기반)"),
                    ("fixed", "지정 출제 (문제 직접 선택)"),
                ],
                default="random",
                max_length=10,
                verbose_name="문제 출제 방식",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="required_tags",
            field=models.ManyToManyField(
                blank=True, to="quiz.tag", verbose_name="출제 포함 태그 (랜덤 방식용)"
            ),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
