# Generated by Django 5.2.7 on 2025-10-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("quiz", "0010_tag_remove_quiz_time_limit_minutes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "verbose_name": "3. 태그",
                "verbose_name_plural": "퀴즈 관리 / 3. 태그",
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="allowed_groups",
            field=models.ManyToManyField(
                blank=True, to="auth.group", verbose_name="응시 가능 그룹"
            ),
        ),
    ]
