# Generated by Django 5.2.7 on 2026-01-11 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_delete_studentlog"),
        ("quiz", "0010_alter_quizattempt_options_alter_useranswer_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentlog",
            options={},
        ),
        migrations.RemoveField(
            model_name="studentlog",
            name="created_by",
        ),
        migrations.AddField(
            model_name="studentlog",
            name="recorder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentlog",
            name="related_quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quiz.quiz",
            ),
        ),
        migrations.AddField(
            model_name="studentlog",
            name="stage",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="studentlog",
            name="action_taken",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentlog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("warning", "⚠️ 경고"),
                    ("warning_letter", "🚫 경고장"),
                    ("counseling", "💬 면담"),
                    ("compliment", "👏 칭찬"),
                    ("etc", "📝 기타"),
                    ("exam_fail", "❌ 시험 불합격"),
                ],
                default="counseling",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studentlog",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_logs",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="studentlog",
            name="reason",
            field=models.TextField(),
        ),
    ]
