# Generated by Django 5.2.7 on 2026-01-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0011_alter_studentlog_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="category",
            field=models.CharField(
                choices=[
                    ("common", "공통 (모든 교육생에게 표시)"),
                    ("process", "공정 (해당 공정 교육생에게 우선 표시)"),
                    ("safety", "안전"),
                    ("etc", "기타"),
                ],
                default="common",
                max_length=10,
                verbose_name="퀴즈 분류",
            ),
        ),
    ]
