# Generated by Django 5.2.7 on 2025-10-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0011_alter_tag_options_quiz_allowed_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="assignment_type",
            field=models.CharField(
                choices=[("개인 요청", "Individual"), ("그룹 배정", "Group")],
                default="개인 요청",
                max_length=10,
            ),
        ),
    ]
