# Generated by Django 5.2.7 on 2025-10-20 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0012_quizattempt_assignment_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"verbose_name": "보기", "verbose_name_plural": "보기"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "문제", "verbose_name_plural": "문제"},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name": "퀴즈", "verbose_name_plural": "퀴즈"},
        ),
        migrations.AlterModelOptions(
            name="quizattempt",
            options={"verbose_name": "응시 요청", "verbose_name_plural": "응시 요청"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "태그", "verbose_name_plural": "태그"},
        ),
        migrations.AlterModelOptions(
            name="testresult",
            options={"verbose_name": "최종 결과", "verbose_name_plural": "최종 결과"},
        ),
        migrations.AlterModelOptions(
            name="useranswer",
            options={
                "verbose_name": "사용자 답변",
                "verbose_name_plural": "사용자 답변",
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="generation_method",
            field=models.CharField(
                choices=[
                    ("랜덤", "난이도별 랜덤 출제"),
                    ("지정", "지정 문제 세트 출제"),
                ],
                default="랜덤",
                max_length=10,
                verbose_name="문제 출제 방식",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.CharField(max_length=200, verbose_name="퀴즈 제목"),
        ),
        migrations.CreateModel(
            name="ExamSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="문제 세트 이름"),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        to="quiz.question", verbose_name="포함된 문제들"
                    ),
                ),
            ],
            options={
                "verbose_name": "문제 세트",
                "verbose_name_plural": "퀴즈 관리 / 5. 문제 세트",
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="exam_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quiz.examsheet",
                verbose_name="선택된 문제 세트",
            ),
        ),
    ]
