# Generated by Django 5.2.7 on 2026-01-30 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_delete_studentlog"),
        ("quiz", "0012_alter_quiz_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={},
        ),
        migrations.RemoveField(
            model_name="notification",
            name="notification_type",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="related_url",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="sender",
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="강의실명")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("large", "대강의실"),
                            ("process", "공정별 강의실"),
                            ("computer", "컴퓨터실"),
                        ],
                        default="process",
                        max_length=20,
                    ),
                ),
                ("capacity", models.IntegerField(default=30, verbose_name="수용인원")),
                (
                    "color",
                    models.CharField(
                        default="#3788d8", max_length=20, verbose_name="달력 표시 색상"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용 가능 여부"),
                ),
                (
                    "target_process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.process",
                        verbose_name="우선 배정 공정",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "process_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("title", models.CharField(max_length=100, verbose_name="사용 목적")),
                ("start_time", models.DateTimeField(verbose_name="시작 시간")),
                ("end_time", models.DateTimeField(verbose_name="종료 시간")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "승인 대기"),
                            ("confirmed", "예약 확정"),
                            ("rejected", "반려됨"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="예약자",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.room",
                        verbose_name="강의실",
                    ),
                ),
            ],
        ),
    ]
