# Generated by Django 5.2.7 on 2025-10-20 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0013_alter_choice_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsheet",
            name="quiz",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.quiz",
                verbose_name="관련 퀴즈",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quiz",
            name="exam_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="quiz.examsheet",
                verbose_name="선택된 문제 세트",
            ),
        ),
    ]
