# Generated by Django 5.2.7 on 2026-01-30 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0013_alter_notification_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "알림",
                "verbose_name_plural": "알림 목록",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                default="general", max_length=50, verbose_name="알림 유형"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="이동할 링크"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="보낸 사람",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="읽음 여부"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(max_length=255, verbose_name="알림 내용"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="받는 사람",
            ),
        ),
    ]
