# Generated by Django 5.2.7 on 2026-01-30 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0014_alter_notification_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="지정 관리자(공동 관리)",
            ),
        ),
    ]
