# Generated by Django 5.2.7 on 2025-10-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0014_examsheet_quiz_alter_quiz_exam_sheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="category",
            field=models.CharField(
                choices=[
                    ("공통", "공통 (모든 교육생에게 표시)"),
                    ("공정", "공정 (해당 공정 교육생에게 우선 표시)"),
                ],
                default="공통",
                max_length=10,
                verbose_name="퀴즈 분류",
            ),
        ),
    ]
