# Generated by Django 5.2.7 on 2025-10-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0015_quiz_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="associated_process",
            field=models.CharField(
                blank=True,
                help_text="퀴즈 분류가 '공정'인 경우에만 이 필드를 채워주세요.",
                max_length=100,
                null=True,
                verbose_name="관련 공정",
            ),
        ),
    ]
