# Generated by Django 5.2.7 on 2026-02-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0015_room_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("general", "일반"),
                    ("signup", "신규가입"),
                    ("exam", "시험요청"),
                    ("work", "근무변경"),
                    ("consult", "면담요청"),
                    ("facility", "시설예약"),
                ],
                default="general",
                max_length=50,
                verbose_name="알림 유형",
            ),
        ),
    ]
