# Generated by Django 5.2.7 on 2026-02-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0016_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_published",
            field=models.BooleanField(
                default=False, verbose_name="공개 여부 (체크 시 응시 가능)"
            ),
        ),
    ]
