# Generated by Django 5.2.7 on 2025-11-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0016_quiz_associated_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="is_pass",
            field=models.BooleanField(default=False, verbose_name="합격 여부"),
        ),
    ]
