# Generated by Django 5.2.7 on 2026-03-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0017_quiz_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="attendees",
            field=models.PositiveIntegerField(default=0, verbose_name="사용 인원"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="업체명"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="process_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="공정명"
            ),
        ),
    ]
