# Generated by Django 5.2.7 on 2025-11-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0017_testresult_is_pass"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
