# Generated by Django 5.2.7 on 2026-03-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0018_reservation_attendees_alter_reservation_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="icon",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="아이콘"
            ),
        ),
    ]
