# Generated by Django 5.2.7 on 2025-11-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0018_quizattempt_started_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizattempt",
            name="started_at",
        ),
    ]
