# Generated by Django 5.2.7 on 2025-11-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0019_remove_quizattempt_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("하", "Easy"), ("중", "Medium"), ("상", "Hard")],
                default="하",
                max_length=2,
                verbose_name="난이도",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="quiz_images/", verbose_name="이미지"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(verbose_name="문제 내용"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("객관식", "Single Choice"),
                    ("다중선택", "Multiple Choice"),
                    ("주관식 (단일정답)", "Short Answer"),
                    ("주관식 (복수정답)", "Short Answer Multiple"),
                ],
                default="객관식",
                max_length=20,
                verbose_name="문제 유형",
            ),
        ),
    ]
