# Generated by Django 5.2.7 on 2026-03-29 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0020_chatroom_chatmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="deleted_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="deleted_chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="hidden_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="hidden_chat_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
