# Generated by Django 5.2.7 on 2025-11-20 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0020_alter_question_difficulty_alter_question_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="특정 인원에게만 이 시험을 지정하고 싶을 때 선택하세요.",
                to=settings.AUTH_USER_MODEL,
                verbose_name="개별 응시 허용 인원",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="required_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="출제 방식이 '태그 조합'일 때, 선택한 태그가 포함된 문제들 중에서만 출제됩니다.",
                to="quiz.tag",
                verbose_name="출제 포함 태그",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="generation_method",
            field=models.CharField(
                choices=[
                    ("랜덤", "난이도별 랜덤 출제 (기본)"),
                    ("지정", "지정 문제 세트 출제"),
                    ("태그", "태그 조합 랜덤 출제"),
                ],
                default="랜덤",
                max_length=10,
                verbose_name="문제 출제 방식",
            ),
        ),
    ]
