# Generated by Django 5.2.7 on 2026-03-29 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0021_chatmessage_deleted_by_chatroom_hidden_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="pinned_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_in_room",
                to="quiz.chatmessage",
            ),
        ),
    ]
