# Generated by Django 5.2.7 on 2025-11-20 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_cohort_evaluationcategory_and_more"),
        ("quiz", "0021_quiz_allowed_users_quiz_required_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="associated_process",
            field=models.ForeignKey(
                blank=True,
                help_text="퀴즈 분류가 '공정'인 경우에만 선택해주세요.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.process",
                verbose_name="관련 공정",
            ),
        ),
    ]
