# Generated by Django 5.2.7 on 2026-03-29 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0022_chatroom_pinned_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="quiz.chatmessage",
            ),
        ),
    ]
