# Generated by Django 5.2.7 on 2026-04-02 12:08

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0023_chatmessage_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatroom",
            options={"ordering": ["-last_activity"]},
        ),
        migrations.AddField(
            model_name="chatroom",
            name="last_activity",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatroom",
            name="pinned_by",
            field=models.ManyToManyField(
                blank=True, related_name="pinned_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
