# Generated by Django 5.2.7 on 2026-04-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0024_alter_chatroom_options_chatroom_last_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentlog",
            name="attached_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="student_logs/",
                verbose_name="경고장/사유서 첨부",
            ),
        ),
    ]
