# Generated by Django 5.2.7 on 2026-04-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0025_studentlog_attached_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="링크 제목")),
                ("url", models.URLField(verbose_name="URL 주소")),
                (
                    "icon",
                    models.CharField(
                        default="bi-box-arrow-up-right",
                        help_text="예: bi-box-arrow-up-right, bi-folder, bi-link 등 (Bootstrap Icon)",
                        max_length=50,
                        verbose_name="아이콘 클래스",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="숫자가 낮을수록 먼저 표시됩니다.",
                        verbose_name="표시 순서",
                    ),
                ),
            ],
            options={
                "verbose_name": "실무 참고 링크",
                "verbose_name_plural": "실무 참고 링크 관리",
                "ordering": ["order", "id"],
            },
        ),
    ]
