# Generated by Django 5.2.7 on 2026-05-15 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_cohort_is_manual_exam_allowed_and_more"),
        ("quiz", "0026_referencelink"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExceptionCompletionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="예외 수료 요청 사유")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "승인 대기"),
                            ("approved", "승인됨"),
                            ("rejected", "반려됨"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청자(매니저)",
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exception_requests",
                        to="accounts.profile",
                        verbose_name="교육생",
                    ),
                ),
            ],
            options={
                "verbose_name": "예외 수료 요청",
                "verbose_name_plural": "예외 수료 요청 목록",
            },
        ),
    ]
