# Generated by Django 5.2.7 on 2026-06-02 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0027_exceptioncompletionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="second_attempt_quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="first_attempt_links",
                to="quiz.quiz",
                verbose_name="2차 재시험 대체용 퀴즈 (예: LAM)",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="third_attempt_quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="second_attempt_links",
                to="quiz.quiz",
                verbose_name="3차 재시험 대체용 퀴즈 (예: CVD)",
            ),
        ),
    ]
