# Generated by Django 5.2.7 on 2026-07-01 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0029_question_approval_status_question_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="approval_status",
        ),
        migrations.RemoveField(
            model_name="question",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="question",
            name="reject_reason",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="requires_approval",
        ),
        migrations.AlterField(
            model_name="quiz",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_quizzes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="담당 매니저",
            ),
        ),
    ]
