# Generated by Django 5.2.7 on 2026-07-01 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0030_remove_question_approval_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("approved", "승인됨 (정상 노출)"),
                    ("pending", "승인 대기중"),
                    ("rejected", "반려됨 (수정 필요)"),
                ],
                default="approved",
                max_length=20,
                verbose_name="승인 상태",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="출제자",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="reject_reason",
            field=models.TextField(blank=True, null=True, verbose_name="반려 사유"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="requires_approval",
            field=models.BooleanField(
                default=False,
                help_text="체크 시, 담당자가 아닌 매니저가 낸 문제는 담당자 승인 전까지 시험에 적용되지 않습니다.",
                verbose_name="문제 출제 승인제 사용",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_quizzes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="지정 담당자 (시험별 출제 관리자)",
            ),
        ),
    ]
