# Generated by Django 5.2.7 on 2025-11-23 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="뱃지 이름")),
                ("description", models.TextField(verbose_name="획득 조건 설명")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="badges/",
                        verbose_name="뱃지 이미지",
                    ),
                ),
            ],
            options={
                "verbose_name": "뱃지",
                "verbose_name_plural": "뱃지",
            },
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="기수 이름 (예: 25-01기)",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="교육 시작일")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="교육 종료일"),
                ),
                (
                    "is_registration_open",
                    models.BooleanField(
                        default=True,
                        help_text="이 옵션을 체크해야 해당 기수 인원이 가입할 수 있습니다.",
                        verbose_name="가입 활성화 여부",
                    ),
                ),
            ],
            options={
                "verbose_name": "기수 (교육 차수)",
                "verbose_name_plural": "기수 (교육 차수)",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="회사 이름"
                    ),
                ),
            ],
            options={
                "verbose_name": "회사",
                "verbose_name_plural": "회사",
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일"
                    ),
                ),
                ("code", models.CharField(max_length=6, verbose_name="인증 코드")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="인증 완료 여부"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="공정 이름"
                    ),
                ),
            ],
            options={
                "verbose_name": "공정",
                "verbose_name_plural": "공정",
            },
        ),
        migrations.CreateModel(
            name="RecordType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="기록 유형 이름"
                    ),
                ),
            ],
            options={
                "verbose_name": "평가 기록 유형",
                "verbose_name_plural": "평가 기록 유형",
            },
        ),
        migrations.CreateModel(
            name="EvaluationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("is_positive", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.evaluationcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="PL 이름"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="성적표 발송 및 알림용",
                        max_length=254,
                        unique=True,
                        verbose_name="PL 이메일",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.company",
                        verbose_name="소속 회사",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.process",
                        verbose_name="담당 공정",
                    ),
                ),
            ],
            options={
                "verbose_name": "PL(파트장)",
                "verbose_name_plural": "PL(파트장)",
            },
        ),
        migrations.CreateModel(
            name="ProcessAccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("approved", "승인됨 (미사용)"),
                            ("expired", "사용완료 (만료)"),
                            ("rejected", "거절됨"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.process",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("employee_id", models.CharField(max_length=50, verbose_name="사번")),
                (
                    "line",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="라인"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("attending", "재직 (응시가능)"),
                            ("counseling", "면담필요 (시험잠김)"),
                            ("dropout", "퇴소 (접속차단)"),
                            ("completed", "수료 (과정완료)"),
                        ],
                        default="attending",
                        max_length=20,
                        verbose_name="현재 상태",
                    ),
                ),
                (
                    "is_manager",
                    models.BooleanField(default=False, verbose_name="매니저 권한 여부"),
                ),
                (
                    "is_pl",
                    models.BooleanField(default=False, verbose_name="PL 권한 여부"),
                ),
                (
                    "is_profile_complete",
                    models.BooleanField(default=False, verbose_name="프로필 작성 완료"),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=False, verbose_name="비밀번호 변경 필요"
                    ),
                ),
                (
                    "badges",
                    models.ManyToManyField(
                        blank=True, to="accounts.badge", verbose_name="획득한 뱃지"
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.cohort",
                        verbose_name="소속 기수",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.company",
                        verbose_name="소속 회사",
                    ),
                ),
                (
                    "pl",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.partleader",
                        verbose_name="담당 PL",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.process",
                        verbose_name="공정",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManagerEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_items",
                    models.ManyToManyField(blank=True, to="accounts.evaluationitem"),
                ),
                (
                    "trainee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "매니저 최종 평가서",
                "verbose_name_plural": "매니저 최종 평가서",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinalAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_avg_score",
                    models.FloatField(default=0, verbose_name="시험 평균(자동)"),
                ),
                (
                    "practice_score",
                    models.FloatField(default=0, verbose_name="실습 점수"),
                ),
                ("note_score", models.FloatField(default=0, verbose_name="노트 점수")),
                (
                    "attitude_score",
                    models.FloatField(default=0, verbose_name="인성/태도 점수"),
                ),
                (
                    "final_score",
                    models.FloatField(default=0, verbose_name="최종 환산 점수"),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="기수 내 등수"
                    ),
                ),
                (
                    "manager_comment",
                    models.TextField(blank=True, verbose_name="최종 코멘트"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_assessment",
                        to="accounts.profile",
                        verbose_name="대상 교육생",
                    ),
                ),
            ],
            options={
                "verbose_name": "최종 종합 평가",
                "verbose_name_plural": "최종 종합 평가",
            },
        ),
        migrations.CreateModel(
            name="EvaluationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="세부 내용")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                        verbose_name="프로필",
                    ),
                ),
                (
                    "record_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.recordtype",
                        verbose_name="기록 유형",
                    ),
                ),
            ],
            options={
                "verbose_name": "수시 평가 기록",
                "verbose_name_plural": "수시 평가 기록",
                "ordering": ["-created_at"],
            },
        ),
    ]
