# Generated by Django 5.2.7 on 2025-11-21 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="뱃지 이름")),
                ("description", models.TextField(verbose_name="획득 조건 설명")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="badges/",
                        verbose_name="뱃지 이미지",
                    ),
                ),
            ],
            options={
                "verbose_name": "뱃지",
                "verbose_name_plural": "뱃지",
            },
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="기수 이름 (예: 25-01기)",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="교육 시작일")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="교육 종료일"),
                ),
                (
                    "is_registration_open",
                    models.BooleanField(
                        default=True,
                        help_text="이 옵션을 체크해야 해당 기수 인원이 가입할 수 있습니다.",
                        verbose_name="가입 활성화 여부",
                    ),
                ),
            ],
            options={
                "verbose_name": "기수 (교육 차수)",
                "verbose_name_plural": "기수 (교육 차수)",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="회사 이름"
                    ),
                ),
            ],
            options={
                "verbose_name": "회사",
                "verbose_name_plural": "회사",
            },
        ),
        migrations.CreateModel(
            name="EvaluationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="평가 항목"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="표시 순서"),
                ),
            ],
            options={
                "verbose_name": "매니저 평가 항목",
                "verbose_name_plural": "매니저 평가 항목 (대분류)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="공정 이름"
                    ),
                ),
            ],
            options={
                "verbose_name": "공정",
                "verbose_name_plural": "공정",
            },
        ),
        migrations.CreateModel(
            name="RecordType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="기록 유형 이름"
                    ),
                ),
            ],
            options={
                "verbose_name": "평가 기록 유형",
                "verbose_name_plural": "평가 기록 유형",
            },
        ),
        migrations.CreateModel(
            name="EvaluationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="평가 예시 (체크할 내용)"
                    ),
                ),
                (
                    "is_positive",
                    models.BooleanField(
                        default=True, verbose_name="긍정/부정 (장점/단점)"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.evaluationcategory",
                        verbose_name="평가 항목",
                    ),
                ),
            ],
            options={
                "verbose_name": "매니저 평가 예시",
                "verbose_name_plural": "매니저 평가 예시 (체크리스트)",
                "ordering": ["category__order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PartLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="PL 이름"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="2회 불합격 시 이 이메일로 알림이 갑니다.",
                        max_length=254,
                        unique=True,
                        verbose_name="PL 이메일",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.company",
                        verbose_name="소속 회사",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.process",
                        verbose_name="담당 공정",
                    ),
                ),
            ],
            options={
                "verbose_name": "PL(파트장)",
                "verbose_name_plural": "PL(파트장)",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("employee_id", models.CharField(max_length=50, verbose_name="사번")),
                (
                    "line",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="라인"
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True,
                        help_text="AI가 생성한 교육생 종합 평가입니다.",
                        null=True,
                        verbose_name="AI 종합 의견",
                    ),
                ),
                (
                    "is_profile_complete",
                    models.BooleanField(default=False, verbose_name="프로필 작성 완료"),
                ),
                (
                    "badges",
                    models.ManyToManyField(
                        blank=True, to="accounts.badge", verbose_name="획득한 뱃지"
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.cohort",
                        verbose_name="소속 기수",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.company",
                        verbose_name="소속 회사",
                    ),
                ),
                (
                    "pl",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.partleader",
                        verbose_name="담당 PL",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.process",
                        verbose_name="공정",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManagerEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_comment",
                    models.TextField(verbose_name="종합 정성 평가 (코멘트)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="평가자 (매니저)",
                    ),
                ),
                (
                    "selected_items",
                    models.ManyToManyField(
                        blank=True,
                        to="accounts.evaluationitem",
                        verbose_name="선택된 평가 항목",
                    ),
                ),
                (
                    "trainee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                        verbose_name="평가 대상 교육생",
                    ),
                ),
            ],
            options={
                "verbose_name": "매니저 최종 평가서",
                "verbose_name_plural": "매니저 최종 평가서",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="세부 내용 (필수)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="기록 일시"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                        verbose_name="프로필",
                    ),
                ),
                (
                    "record_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.recordtype",
                        verbose_name="기록 유형",
                    ),
                ),
            ],
            options={
                "verbose_name": "평가 기록",
                "verbose_name_plural": "평가 기록",
                "ordering": ["-created_at"],
            },
        ),
    ]
