# Generated by Django 5.2.7 on 2025-10-11 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("employee_id", models.CharField(max_length=50, verbose_name="사번")),
                ("class_number", models.CharField(max_length=50, verbose_name="기수")),
                ("process", models.CharField(max_length=100, verbose_name="공정")),
                ("pl_name", models.CharField(max_length=50, verbose_name="PL님 성함")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
