# Generated by Django 5.2.7 on 2025-10-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="뱃지 이름")),
                ("description", models.TextField(verbose_name="획득 조건 설명")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="badges/",
                        verbose_name="뱃지 이미지",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="badges",
            field=models.ManyToManyField(
                blank=True, to="accounts.badge", verbose_name="획득한 뱃지"
            ),
        ),
    ]
