# Generated by Django 5.2.7 on 2025-11-23 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evaluationcategory",
            options={
                "ordering": ["order"],
                "verbose_name": "평가 항목 (대분류)",
                "verbose_name_plural": "평가 항목 (대분류)",
            },
        ),
        migrations.AlterModelOptions(
            name="evaluationitem",
            options={
                "ordering": ["category__order", "id"],
                "verbose_name": "평가 세부 항목 (체크리스트)",
                "verbose_name_plural": "평가 세부 항목 (체크리스트)",
            },
        ),
        migrations.AlterField(
            model_name="evaluationcategory",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="평가 항목"
            ),
        ),
        migrations.AlterField(
            model_name="evaluationcategory",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="표시 순서"),
        ),
        migrations.AlterField(
            model_name="evaluationitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.evaluationcategory",
                verbose_name="평가 항목",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationitem",
            name="description",
            field=models.CharField(
                max_length=255, verbose_name="평가 예시 (체크할 내용)"
            ),
        ),
        migrations.AlterField(
            model_name="evaluationitem",
            name="is_positive",
            field=models.BooleanField(
                default=True, verbose_name="긍정/부정 (장점/단점)"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="employee_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="사번"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="이름"
            ),
        ),
    ]
