# Generated by Django 5.2.7 on 2025-11-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_badge_profile_badges"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={"verbose_name": "뱃지", "verbose_name_plural": "뱃지"},
        ),
    ]
