# Generated by Django 5.2.7 on 2025-11-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_processaccessrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processaccessrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기중"),
                    ("approved", "승인됨 (미사용)"),
                    ("expired", "사용완료 (만료)"),
                    ("rejected", "거절됨"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
