# Generated by Django 5.2.7 on 2025-12-06 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_evaluationcategory_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.IntegerField(
                        choices=[
                            (1, "1차 면담 (교수/센터장)"),
                            (2, "2차 면담 (파트장/PL)"),
                            (3, "3차 면담 (퇴소/최종)"),
                        ],
                        verbose_name="면담 차수",
                    ),
                ),
                ("content", models.TextField(verbose_name="면담 내용 (한줄평)")),
                (
                    "opinion",
                    models.TextField(
                        blank=True,
                        help_text="예: 경고 조치, 기회 부여, 퇴소 처리 등",
                        verbose_name="조치 의견",
                    ),
                ),
                (
                    "is_passed",
                    models.BooleanField(
                        default=False,
                        help_text="체크해야 다음 단계(시험/면담)가 활성화됩니다.",
                        verbose_name="통과/완료 여부",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="면담 진행자",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="accounts.profile",
                        verbose_name="대상 교육생",
                    ),
                ),
            ],
            options={
                "verbose_name": "면담 기록",
                "verbose_name_plural": "면담 기록 (단계별)",
                "ordering": ["profile", "stage"],
                "unique_together": {("profile", "stage")},
            },
        ),
    ]
