# Generated by Django 5.2.7 on 2025-11-01 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_badge_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="회사 이름"
                    ),
                ),
            ],
            options={
                "verbose_name": "회사",
                "verbose_name_plural": "교육생 관리 / 4. 회사",
            },
        ),
        migrations.AlterModelOptions(
            name="badge",
            options={
                "verbose_name": "뱃지",
                "verbose_name_plural": "교육생 관리 / 3. 뱃지",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.company",
                verbose_name="소속 회사",
            ),
        ),
    ]
