# Generated by Django 5.2.7 on 2025-11-22 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_processaccessrequest_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processaccessrequest",
            name="requester",
        ),
        migrations.AlterField(
            model_name="processaccessrequest",
            name="target_process",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.process",
            ),
        ),
    ]
