# Generated by Django 5.2.7 on 2025-12-07 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_interview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="warning_count",
            field=models.IntegerField(default=0, verbose_name="누적 경고 횟수"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[
                    ("attending", "재직 (정상)"),
                    ("caution", "주의 (경고 1회)"),
                    ("counseling", "면담필요 (잠금)"),
                    ("dropout", "퇴소 (차단)"),
                    ("completed", "수료 (과정완료)"),
                ],
                default="attending",
                max_length=20,
                verbose_name="현재 상태",
            ),
        ),
        migrations.CreateModel(
            name="StudentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("warning", "⚠️ 일반 경고"),
                            ("warning_letter", "⛔ 경고장 발부"),
                            ("exam_fail", "📉 시험 불합격"),
                            ("counseling", "💬 면담 및 조치"),
                            ("compliment", "👍 칭찬/우수"),
                        ],
                        max_length=20,
                        verbose_name="기록 유형",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="경고 사유, 면담 내용 등을 상세히 기록하세요.",
                        verbose_name="사유 및 내용",
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(blank=True, null=True, verbose_name="조치 사항"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="조치 완료 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="accounts.profile",
                        verbose_name="대상 교육생",
                    ),
                ),
                (
                    "recorder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="기록자",
                    ),
                ),
            ],
            options={
                "verbose_name": "학생 특이사항 로그",
                "verbose_name_plural": "학생 특이사항 로그",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Interview",
        ),
    ]
