# Generated by Django 5.2.7 on 2025-11-22 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_processaccessrequest_requester_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="processaccessrequest",
            name="requester",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_requests",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="매니저 권한 여부"),
        ),
        migrations.AlterField(
            model_name="processaccessrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기중"),
                    ("approved", "승인됨 (미사용)"),
                    ("expired", "사용완료 (만료)"),
                    ("rejected", "거절됨"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
