# Generated by Django 5.2.7 on 2025-11-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_company_alter_badge_options_profile_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={"verbose_name": "뱃지", "verbose_name_plural": "뱃지"},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "회사", "verbose_name_plural": "회사"},
        ),
        migrations.CreateModel(
            name="EvaluationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("경고", "경고 (경고장)"),
                            ("시상", "시상"),
                            ("연차", "연차"),
                            ("기타휴가", "기타 (연비군 등)"),
                            ("기타", "기타 특이사항"),
                        ],
                        default="기타",
                        max_length=20,
                        verbose_name="기록 유형",
                    ),
                ),
                ("description", models.TextField(verbose_name="세부 내용 (필수)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="기록 일시"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                        verbose_name="프로필",
                    ),
                ),
            ],
            options={
                "verbose_name": "평가 기록",
                "verbose_name_plural": "평가 기록",
                "ordering": ["-created_at"],
            },
        ),
    ]
