# Generated by Django 5.2.7 on 2025-12-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_warning_count_alter_profile_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="joined_at",
            field=models.DateField(
                blank=True,
                help_text="연차 계산 기준일입니다.",
                null=True,
                verbose_name="입사일(교육시작일)",
            ),
        ),
        migrations.AlterField(
            model_name="studentlog",
            name="action_taken",
            field=models.TextField(
                blank=True,
                help_text="경고 후 조치된 내용이나 합의 사항",
                null=True,
                verbose_name="조치 사항",
            ),
        ),
    ]
