# Generated by Django 5.2.7 on 2025-11-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_processaccessrequest_requester_profile_is_manager_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="must_change_password",
            field=models.BooleanField(default=False, verbose_name="비밀번호 변경 필요"),
        ),
    ]
