# Generated by Django 5.2.7 on 2025-11-08 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_badge_options_alter_company_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="항목명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="활성화 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "평가 항목",
                "verbose_name_plural": "평가 항목",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="evaluationrecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("경고", "경고 (경고장)"),
                    ("시상", "시상"),
                    ("연차", "연차"),
                    ("기타휴가", "기타 (연비군 등)"),
                    ("기타", "기타 특이사항"),
                ],
                default="기타",
                help_text="기존 호환용 필드. 새 관리형 항목이 있으면 항목을 사용하세요.",
                max_length=20,
                verbose_name="기록 유형",
            ),
        ),
        migrations.AddField(
            model_name="evaluationrecord",
            name="evaluation_item",
            field=models.ForeignKey(
                blank=True,
                help_text="관리자가 생성한 평가 항목을 선택하면 항목명이 표시됩니다.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.evaluationitem",
                verbose_name="평가 항목",
            ),
        ),
    ]
