# Generated by Django 5.2.7 on 2025-12-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_joined_at_alter_studentlog_action_taken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentLog",
        ),
    ]
