# Generated by Django 5.2.7 on 2026-01-11 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_delete_studentlog"),
        ("quiz", "0010_alter_quizattempt_options_alter_useranswer_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("warning", "⚠️ 경고 (Warning)"),
                            ("warning_letter", "🚫 경고장 발부"),
                            ("counseling", "💬 면담/상담"),
                            ("compliment", "👏 칭찬/우수"),
                            ("etc", "📝 기타 특이사항"),
                            ("exam_fail", "❌ 시험 불합격"),
                        ],
                        default="counseling",
                        max_length=20,
                        verbose_name="기록 유형",
                    ),
                ),
                ("reason", models.TextField(verbose_name="사유 및 내용")),
                (
                    "action_taken",
                    models.TextField(blank=True, null=True, verbose_name="조치 사항"),
                ),
                (
                    "stage",
                    models.IntegerField(
                        default=1, verbose_name="경고 단계 (1차/2차/3차)"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="조치 완료 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_logs",
                        to="accounts.profile",
                        verbose_name="대상 학생",
                    ),
                ),
                (
                    "recorder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="기록자(관리자)",
                    ),
                ),
                (
                    "related_quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz.quiz",
                        verbose_name="관련 시험",
                    ),
                ),
            ],
            options={
                "verbose_name": "학생 특이사항/로그",
                "verbose_name_plural": "학생 특이사항/로그",
                "ordering": ["-created_at"],
            },
        ),
    ]
