# Generated by Django 5.2.7 on 2025-11-08 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0007_partleader_remove_evaluationrecord_evaluation_item_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="partleader",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.company",
                verbose_name="소속 회사",
            ),
        ),
        migrations.AddField(
            model_name="partleader",
            name="line",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="라인"
            ),
        ),
        migrations.AddField(
            model_name="partleader",
            name="process",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="담당 공정"
            ),
        ),
    ]
