# Generated by Django 5.2.7 on 2026-01-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_studentlog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentLog",
        ),
    ]
