# Generated by Django 5.2.7 on 2025-11-09 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_partleader_company_partleader_line_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="공정 이름"
                    ),
                ),
            ],
            options={
                "verbose_name": "공정",
                "verbose_name_plural": "공정",
            },
        ),
        migrations.CreateModel(
            name="RecordType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="기록 유형 이름"
                    ),
                ),
            ],
            options={
                "verbose_name": "평가 기록 유형",
                "verbose_name_plural": "평가 기록 유형",
            },
        ),
        migrations.RemoveField(
            model_name="partleader",
            name="line",
        ),
        migrations.AddField(
            model_name="profile",
            name="ai_summary",
            field=models.TextField(
                blank=True,
                help_text="AI가 생성한 교육생 종합 평가입니다.",
                null=True,
                verbose_name="AI 종합 의견",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="line",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="라인"
            ),
        ),
        migrations.AlterField(
            model_name="partleader",
            name="email",
            field=models.EmailField(
                help_text="2회 불합격 시 이 이메일로 알림이 갑니다.",
                max_length=254,
                unique=True,
                verbose_name="PL 이메일",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="process",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.process",
                verbose_name="공정",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationrecord",
            name="record_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.recordtype",
                verbose_name="기록 유형",
            ),
        ),
    ]
