# Generated by Django 5.2.7 on 2026-02-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_profile_is_approved_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partleader",
            name="process",
        ),
        migrations.AddField(
            model_name="partleader",
            name="process",
            field=models.ManyToManyField(
                blank=True, to="accounts.process", verbose_name="담당 공정들"
            ),
        ),
    ]
