# Generated by Django 5.2.7 on 2025-11-11 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_process_recordtype_remove_partleader_line_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partleader",
            name="process",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.process",
                verbose_name="담당 공정",
            ),
        ),
    ]
