# Generated by Django 5.2.7 on 2026-03-17 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_partleader_process_partleader_process"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="평가 마감 완료"),
        ),
        migrations.CreateModel(
            name="DropOutRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drop_date", models.DateField(verbose_name="퇴사/퇴소(예정)일")),
                ("reason", models.TextField(verbose_name="퇴사/퇴소 사유")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "승인 대기"),
                            ("approved", "승인 완료"),
                            ("rejected", "반려됨"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="결재 상태",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="결재 처리일시"
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청 매니저",
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropout_records",
                        to="accounts.profile",
                        verbose_name="대상 교육생",
                    ),
                ),
            ],
            options={
                "verbose_name": "중도 퇴사 요청",
                "verbose_name_plural": "중도 퇴사 요청 관리",
            },
        ),
    ]
