# Generated by Django 5.2.7 on 2025-11-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_partleader_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_profile_complete",
            field=models.BooleanField(default=False, verbose_name="프로필 작성 완료"),
        ),
    ]
