# Generated by Django 5.2.7 on 2025-11-19 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_profile_is_profile_complete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="기수 이름 (예: 25-01기)",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="교육 시작일")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="교육 종료일"),
                ),
                (
                    "is_registration_open",
                    models.BooleanField(
                        default=True,
                        help_text="이 옵션을 체크해야 해당 기수 인원이 가입할 수 있습니다.",
                        verbose_name="가입 활성화 여부",
                    ),
                ),
            ],
            options={
                "verbose_name": "기수 (교육 차수)",
                "verbose_name_plural": "기수 (교육 차수)",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="평가 항목"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="표시 순서"),
                ),
            ],
            options={
                "verbose_name": "매니저 평가 항목",
                "verbose_name_plural": "매니저 평가 항목 (대분류)",
                "ordering": ["order"],
            },
        ),
        migrations.RemoveField(
            model_name="profile",
            name="class_number",
        ),
        migrations.AddField(
            model_name="profile",
            name="cohort",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.cohort",
                verbose_name="소속 기수",
            ),
        ),
        migrations.CreateModel(
            name="EvaluationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="평가 예시 (체크할 내용)"
                    ),
                ),
                (
                    "is_positive",
                    models.BooleanField(
                        default=True, verbose_name="긍정/부정 (장점/단점)"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.evaluationcategory",
                        verbose_name="평가 항목",
                    ),
                ),
            ],
            options={
                "verbose_name": "매니저 평가 예시",
                "verbose_name_plural": "매니저 평가 예시 (체크리스트)",
                "ordering": ["category__order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ManagerEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_comment",
                    models.TextField(verbose_name="종합 정성 평가 (코멘트)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="평가자 (매니저)",
                    ),
                ),
                (
                    "selected_items",
                    models.ManyToManyField(
                        blank=True,
                        to="accounts.evaluationitem",
                        verbose_name="선택된 평가 항목",
                    ),
                ),
                (
                    "trainee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                        verbose_name="평가 대상 교육생",
                    ),
                ),
            ],
            options={
                "verbose_name": "매니저 최종 평가서",
                "verbose_name_plural": "매니저 최종 평가서",
                "ordering": ["-created_at"],
            },
        ),
    ]
