# Generated by Django 5.2.7 on 2026-03-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_cohort_is_closed_dropoutrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[
                    ("attending", "재직 (정상)"),
                    ("caution", "주의 (경고 1회)"),
                    ("counseling", "면담필요 (잠금)"),
                    ("dropout", "미수료 및 퇴소"),
                    ("completed", "수료 (과정완료)"),
                ],
                default="attending",
                max_length=20,
                verbose_name="현재 상태",
            ),
        ),
    ]
