# Generated by Django 5.2.7 on 2026-03-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_profile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="session_key",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="현재 세션 키"
            ),
        ),
    ]
