# Generated by Django 5.2.7 on 2026-03-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_profile_session_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="processaccessrequest",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="권한 만료 일시"
            ),
        ),
    ]
