# Generated by Django 5.2.7 on 2026-03-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_processaccessrequest_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="can_use_messenger",
            field=models.BooleanField(default=True, verbose_name="메신저 사용 가능"),
        ),
    ]
