# Generated by Django 5.2.7 on 2026-04-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_profile_can_use_messenger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="can_use_messenger",
            field=models.BooleanField(
                default=False, verbose_name="사내 메신저 사용 가능"
            ),
        ),
    ]
