# Generated by Django 5.2.7 on 2026-04-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_profile_can_use_messenger"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="is_manual_exam_allowed",
            field=models.BooleanField(
                default=False,
                help_text="체크 시 매니저/PL이 공통시험 점수를 수기로 일괄 입력할 수 있습니다.",
                verbose_name="공통시험 수기 채점 허용",
            ),
        ),
        migrations.AlterField(
            model_name="cohort",
            name="is_registration_open",
            field=models.BooleanField(default=True, verbose_name="가입 활성화 여부"),
        ),
    ]
