# Generated by Django 5.2.7 on 2026-06-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_cohort_is_manual_exam_allowed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="is_process_manual_exam_allowed",
            field=models.BooleanField(
                default=False, verbose_name="공정시험 수기 채점 허용"
            ),
        ),
    ]
