# Generated by Django 5.2.7 on 2026-06-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_cohort_is_process_manual_exam_allowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalassessment",
            name="practice_score_1",
            field=models.FloatField(
                blank=True, null=True, verbose_name="실습 1차 점수"
            ),
        ),
        migrations.AddField(
            model_name="finalassessment",
            name="practice_score_2",
            field=models.FloatField(
                blank=True, null=True, verbose_name="실습 2차 점수"
            ),
        ),
        migrations.AddField(
            model_name="finalassessment",
            name="practice_score_3",
            field=models.FloatField(
                blank=True, null=True, verbose_name="실습 3차 점수"
            ),
        ),
        migrations.AlterField(
            model_name="finalassessment",
            name="practice_score",
            field=models.FloatField(default=0, verbose_name="최종 실습 점수"),
        ),
    ]
