"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
[https://docs.djangoproject.com/en/5.2/topics/settings/](https://docs.djangoproject.com/en/5.2/topics/settings/)

For the full list of settings and their values, see
[https://docs.djangoproject.com/en/5.2/ref/settings/](https://docs.djangoproject.com/en/5.2/ref/settings/)
"""


import os
import dj_database_url  # 맨 위에 import 추가
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See [https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/](https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/)


# [수정 1] Django의 비밀 키를 환경 변수에서 가져오기
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# [수정 2] 배포 환경(Render)에서는 DEBUG = False
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# [수정 3] Render의 웹사이트 주소(.onrender.com)를 허용
ALLOWED_HOSTS = []
if not DEBUG:
    ALLOWED_HOSTS.append('.onrender.com')

# Application definition
INSTALLED_APPS = [
    'channels',
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', 
    'accounts.apps.AccountsConfig',
    'quiz.apps.QuizConfig',
    'whitenoise.runserver_nostatic', # WhiteNoise
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # WhiteNoise
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# [수정 5] 데이터베이스 설정을 Render의 PostgreSQL URL에서 가져오기
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# 만약 DATABASE_URL 환경 변수가 세팅되어 있다면 (Render 환경)
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.parse(os.environ.get('DATABASE_URL'))
# Password validation
# [https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators](https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators)

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
# [https://docs.djangoproject.com/en/5.2/topics/i18n/](https://docs.djangoproject.com/en/5.2/topics/i18n/)

LANGUAGE_CODE = 'ko-kr'
TIME_ZONE = 'Asia/Seoul'
USE_I18N = True
USE_TZ = True



# [수정 6] 정적 파일(Static) 설정 (Whitenoise)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# [수정 7] 미디어 파일(Media) 설정 (Cloudflare R2)
if not DEBUG:
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')
    AWS_S3_REGION_NAME = 'auto'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_DEFAULT_ACL = None
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/media/'
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- 핵심 기능 설정 ---
LOGIN_REDIRECT_URL = '/quiz/mypage/'
LOGOUT_REDIRECT_URL = '/accounts/login/' 

# ASGI & Channels (실시간 알림)
ASGI_APPLICATION = 'config.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# 자동 로그아웃 (3시간)
SESSION_COOKIE_AGE = 10800
SESSION_SAVE_EVERY_REQUEST = True

# Admin Interface (테마 및 그룹화)
ADMIN_INTERFACE_SETTINGS = {
    'TITLE': 'CBT 관리자 서버',
    'SHOW_HEADER': True,
    'SHOW_SIDEMENU': True,
}
ADMIN_INTERFACE_MODELS_GROUP_BY_CATEGORY = [
    {
        "name": "교육생 관리",
        "models": ["auth.User", "auth.Group", "accounts.Profile", "accounts.Badge", "accounts.Company", "accounts.EvaluationRecord","accounts.PartLeader",],
    },
    {
        "name": "퀴즈 관리",
        "models": ["quiz.Quiz", "quiz.Question", "quiz.Choice", "quiz.Tag", "quiz.ExamSheet"],
    },
    {
        "name": "시험 결과 관리",
        "models": ["quiz.QuizAttempt", "quiz.TestResult", "quiz.UserAnswer"],
    },
    {
        "name": "사이트 설정",
        "models": ["admin_interface.Theme", "sites.Site"]
    }
]

# 비밀번호 재설정 이메일 설정
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

# Django Sites 프레임워크
SITE_ID = 1

