# Generated by Django 5.2.7 on 2025-12-06 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_evaluationcategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="날짜")),
                (
                    "mdm_image",
                    models.ImageField(
                        upload_to="mdm_proofs/%Y/%m/%d/", verbose_name="MDM 스크린샷"
                    ),
                ),
                (
                    "captured_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="OCR 인식 시간"
                    ),
                ),
                (
                    "security_status",
                    models.CharField(
                        choices=[
                            ("safe", "보안 준수 (녹색/적색/황색)"),
                            ("violation", "보안 위반 (파란색/해제)"),
                            ("unknown", "판독 불가"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="보안 상태",
                    ),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("present", "출석 (정상)"),
                            ("late", "지각"),
                            ("absent", "결석"),
                            ("vacation", "휴가/공가"),
                            ("error", "인증 실패 (재요청)"),
                        ],
                        default="absent",
                        max_length=20,
                        verbose_name="근태 상태",
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(blank=True, verbose_name="관리자 코멘트"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                        verbose_name="교육생",
                    ),
                ),
            ],
            options={
                "verbose_name": "일일 근태/보안 기록",
                "verbose_name_plural": "일일 근태/보안 기록",
                "ordering": ["-date"],
                "unique_together": {("profile", "date")},
            },
        ),
    ]
