# Generated by Django 5.2.7 on 2025-12-06 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_interview"),
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="근무 명칭")),
                ("short_name", models.CharField(max_length=10, verbose_name="약어")),
                (
                    "color",
                    models.CharField(
                        default="#FFFFFF", max_length=7, verbose_name="표시 색상(HEX)"
                    ),
                ),
                (
                    "deduction",
                    models.FloatField(default=0.0, verbose_name="연차 차감일수"),
                ),
                (
                    "is_working_day",
                    models.BooleanField(default=True, verbose_name="출근 인정 여부"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬 순서"),
                ),
            ],
            options={
                "verbose_name": "근무 유형 설정",
                "verbose_name_plural": "근무 유형 설정",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LeaveQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_leave",
                    models.FloatField(default=15.0, verbose_name="총 연차"),
                ),
                (
                    "used_leave",
                    models.FloatField(default=0.0, verbose_name="사용 연차"),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                        verbose_name="교육생",
                    ),
                ),
            ],
            options={
                "verbose_name": "연차 현황",
                "verbose_name_plural": "연차 현황",
            },
        ),
        migrations.CreateModel(
            name="ScheduleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="변경 대상 날짜")),
                ("reason", models.TextField(verbose_name="변경 사유 (필수)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("approved", "승인됨"),
                            ("rejected", "거절됨"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="승인자",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_requests",
                        to="accounts.profile",
                    ),
                ),
                (
                    "target_work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.worktype",
                        verbose_name="변경할 근무",
                    ),
                ),
            ],
            options={
                "verbose_name": "근무 변경 요청",
                "verbose_name_plural": "근무 변경 요청",
            },
        ),
        migrations.CreateModel(
            name="DailySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "mdm_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="mdm_proofs/%Y/%m/%d/",
                        verbose_name="MDM 인증샷",
                    ),
                ),
                (
                    "captured_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="OCR 인식 시간"
                    ),
                ),
                (
                    "is_late",
                    models.BooleanField(default=False, verbose_name="지각 여부"),
                ),
                (
                    "is_absent",
                    models.BooleanField(default=False, verbose_name="결석 여부"),
                ),
                (
                    "is_mdm_verified",
                    models.BooleanField(default=False, verbose_name="보안 인증 완료"),
                ),
                (
                    "memo",
                    models.CharField(blank=True, max_length=200, verbose_name="비고"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                        verbose_name="교육생",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attendance.worktype",
                        verbose_name="근무 일정",
                    ),
                ),
            ],
            options={
                "verbose_name": "일별 근태 스케줄",
                "verbose_name_plural": "일별 근태 스케줄",
                "ordering": ["date"],
                "unique_together": {("profile", "date")},
            },
        ),
        migrations.DeleteModel(
            name="DailyAttendance",
        ),
    ]
