# Generated by Django 5.2.7 on 2026-02-02 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="daily_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendance.dailyschedule",
            ),
        ),
    ]
